# Generated by Django 3.0.6 on 2020-08-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quiz',
            new_name='test',
        ),
    ]
